### ISSUE TITLE
Download videos only from the last 24 hours?

### ISSUE THREAD

**Issue by Root-FTW** [damirTAG/TikTok-Module#1]
In the tiktok mobile app, it is possible to search for example Fortnite and filter only the videos that have been uploaded in the last 24 hours, is it possible to do this with your project? I would like to download all the videos uploaded in the last 24 hours that contain the word fortnite.

**Comment by damirtag** [comment]
Unfortunately, for this moment my project cant do that. But if I find out how to do it, I’ll definitely do it!

**Comment by Root-FTW** [comment]
> Unfortunately, for this moment my project cant do that. But if I find out how to do it, I’ll definitely do it!

Please, I hope you can make it, that would be very useful.
